### ISSUE TITLE
Something wrong with grtde simulation and star setup

### ISSUE THREAD

**Issue by Shigaharuki3012** [danieljprice/phantom#465] opened 2023-09-07 09:40 UTC
When I run grtde simulation setup,errors appeared like:
```
reading setup options from grtde.setup
 opening database from grtde.setup with 11 entries
 ERROR: tol_ekin not found
 ERROR: maxits not found
  2 error(s) during read of setup file: re-writing...
 writing setup options file grtde.setup
  Edit grtde.setup and rerun phantomsetup
```
though the file would be completed shortly after running this.
Also,I recommend that setups for star  in **grtde.setup**  should be added during grtde simulation,but now we can not setup more parameters except several options.For example ,we can not set the code unit because the default **Msun** has been determined.(see below)

```
# input file for tidal disruption setup

# options for star 
            iprofile =           2    ! 0=Sink,1=Unif,2=Poly,3=Dens,4=KEPL,5=MESA,6=Pie
               Mstar =       1.000    ! mass of star  [Msun]
               Rstar =       1.000    ! radius of star [Rsun]
                  np =       10000    ! number of particles
               relax =           T    ! relax star into hydrostatic equilibrium
            tol_ekin =   1.000E-07    ! tolerance on ekin/epot to stop relaxation
              maxits =        1000    ! maximum number of relaxation iterations

# options for black hole and orbit
               mhole =   1.000E+06    ! mass of black hole (solar mass)
                beta =       5.000    ! penetration factor
                 ecc =       0.950    ! eccentricity (1 for parabolic)
             norbits =       5.000    ! number of orbits
       dumpsperorbit =         100    ! number of dumps per orbit
               theta =         60.    ! inclination of orbit (degrees)
```

**Comment by danieljprice** [comment] 2023-10-09 22:00
I'm not sure what the issue is here, you are in the GR code so you must have G=M=c=1 and the only unit freedom is to set the mass unit, typically we set M=1 for the black hole. Please clarify exactly what the problem is?

**Comment by tajjankovic** [comment] 2024-02-28 10:27
I can reproduce the issue described above during the relaxation process for SETUP=grtde:

> FATAL ERROR! cons2prim: could not solve rootfinding on particle...

star.setup parameters I used:

# options for star 
            iprofile =           2    ! 0=Sink,1=Unif,2=Poly,3=Dens,4=KEPL,5=MESA,6=Pie
               Mstar =       1.000    ! mass of star  [Msun]
               Rstar =       1.000    ! radius of star [Rsun]
                  np =       100000    ! number of particles
               relax =           T    ! relax star into hydrostatic equilibrium
            tol_ekin =   1.000E-07    ! tolerance on ekin/epot to stop relaxation
              maxits =        1000    ! maximum number of relaxation iterations

# options for black hole and orbit
               mhole =   1.000E+06    ! mass of black hole (solar mass)
                beta =       5.000    ! penetration factor
                 ecc =       0.800    ! eccentricity (1 for parabolic)
             norbits =       5.000    ! number of orbits
       dumpsperorbit =         100    ! number of dumps per orbit
               theta =       0.000    ! inclination of orbit (degrees)


Steps to reproduce the error: **$PHANTOM_DIR/scripts/writemake.sh grtde>Makefile;make setup;make;./phantomsetup star**
Error: 

>  FATAL ERROR! cons2prim: could not solve rootfinding on particle 50005
>   pmom =   0.0000000000000000        0.0000000000000000        0.0000000000000000     
>   rho* =   3.2251316183968794E-006
> 
> Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

**Comment by danieljprice** [comment] 2024-04-24 01:57
definitely most people have set up an isolated star followed by the moddump_tde procedure to place it in orbit. The one-stop setup_grtde procedure is new... I'm not sure what is going wrong here. In the meantime I'd suggest to fall back to the "regular" SETUP=grstar followed by moddump procedure if it's not working for you..

**Comment by tajjankovic** [comment] 2024-04-24 06:23
Hey Daniel,

I also found these notes from the ANITA workshop (
https://docs.google.com/document/d/1fuDLLb6TNPg_cBpCyQvBuwt3jqTehIgIjfffu3N4dEE/edit#heading=h.sbscbncuhxte),
which might prove helpful. Here it's instructed to uncomment this line for
the relaxation process.

Cheers,
Taj

**Comment by Shigaharuki3012** [comment] 2024-04-30 08:00
> I'm not sure what the issue is here, you are in the GR code so you must have G=M=c=1 and the only unit freedom is to set the mass unit, typically we set M=1 for the black hole. Please clarify exactly what the problem is?
> 
> Is the problem you get NaNs on relaxing the star? If so exactly what parameters are needed to reproduce this?

Sorry for making the problem not so clear...I realized that was not a problem at all :)
And thanks for @tajjankovic to reproduce the issue.

**Comment by danieljprice** [comment] 2024-05-14 18:08
I tracked this down, it was broken in 09e337c1b2 . The solution is to uncomment the relevant line in derivs.F90, as outlined by @tajjankovic . I will push a fix for this, I think it just needs to be not called for the case where the metric is tabulated.

**Closed** 2024-05-14 22:01 UTC
