### ISSUE TITLE
sedov test reports B-cleaning controlling timestep

### ISSUE THREAD

**Issue by danieljprice** [danieljprice/phantom#4] opened 2020-06-03 04:25 UTC
The sedov test seems to broken by recent changes to the div B cleaning. For example, running the following command on my laptop:

```make SETUP=testkd && ./bin/phantom test sedov```

gives the output:
```
--> testing Sedov blast wave

 ---------------- particles set on  16 x  16 x  16 uniform cubic lattice --------------
  x:  -0.500    ->  0.500       y:  -0.500    ->  0.500       z:  -0.500    ->  0.500     
 dx:   6.250E-02               dy:   6.250E-02               dz:   6.250E-02
 -----------------------------------------------------------------------------------------

  npart =         4096  particle mass =    2.4414062500000000E-004
 WARNING! force: radiation may become negative, limiting timestep
 WARNING! force: radiation may become negative, limiting timestep
 WARNING! force: radiation may become negative, limiting timestep
 WARNING! force: radiation may become negative, limiting timestep
 WARNING! force: radiation may become negative, limiting timestep
 WARNING! force: radiation may become negative, limiting timestep
 WARNING! force: radiation may become negative, limiting timestep
 WARNING! force: radiation may become negative, limiting timestep
 B-cleaning controlling timestep on           56  particles
 WARNING! force: radiation may become negative, limiting timestep
 (buffering remaining warnings... radiation may become negative, limiting timestep) 
 B-cleaning controlling timestep on           56  particles
> step 1 / 256 t = 0.3906250E-03 dt = 3.91E-04 moved 4096 in 0.11 cpu-s < | np = 4096 |

 B-cleaning controlling timestep on           56  particles
> step 2 / 256 t = 0.7812500E-03 dt = 3.91E-04 moved 4096 in 0.12 cpu-s <
 WARNING! evolve: N gas particles with energy = 0 : N = 1664

 B-cleaning controlling timestep on           56  particles
> step 3 / 256 t = 0.1171875E-02 dt = 3.91E-04 moved 56 in 0.0064 cpu-s <

 radiation diffusion controlling timestep on           72  particles
 B-cleaning controlling timestep on           56  particles
> step 4 / 256 t = 0.1562500E-02 dt = 3.91E-04 moved 4096 in 0.11 cpu-s <

 B-cleaning controlling timestep on           56  particles
> step 5 / 256 t = 0.1953125E-02 dt = 3.91E-04 moved 56 in 0.0071 cpu-s <

 radiation diffusion controlling timestep on            8  particles
 B-cleaning controlling timestep on           56  particles
> step 6 / 256 t = 0.2343750E-02 dt = 3.91E-04 moved 400 in 0.018 cpu-s <

 B-cleaning controlling timestep on           56  particles
> step 7 / 256 t = 0.2734375E-02 dt = 3.91E-04 moved 64 in 0.0066 cpu-s <

 B-cleaning controlling timestep on           64  particles
> step 8 / 256 t = 0.3125000E-02 dt = 3.91E-04 moved 4096 in 0.11 cpu-s <
 WARNING! evolve: N gas particles with energy = 0 : N = 160

 B-cleaning controlling timestep on           56  particles
> step 9 / 256 t = 0.3515625E-02 dt = 3.91E-04 moved 56 in 0.0065 cpu-s <

 B-cleaning controlling timestep on           64  particles
> step 10 / 256 t = 0.3906250E-02 dt = 3.91E-04 moved 408 in 0.016 cpu-s <

 B-cleaning controlling timestep on           32  particles
> step 11 / 256 t = 0.4296875E-02 dt = 3.91E-04 moved 32 in 0.0047 cpu-s <

 radiation diffusion controlling timestep on          120  particles
 B-cleaning controlling timestep on           64  particles
> step 12 / 256 t = 0.4687500E-02 dt = 3.91E-04 moved 2488 in 0.070 cpu-s <
 WARNING! evolve: N gas particles with energy = 0 : N = 160

> step 49 / 1024 t = 0.4785156E-02 dt = 9.77E-05 moved 24 in 0.0048 cpu-s <

 radiation diffusion controlling timestep on           48  particles
> step 50 / 1024 t = 0.4882812E-02 dt = 9.77E-05 moved 1128 in 0.035 cpu-s <
 WARNING! evolve: N gas particles with energy = 0 : N = 160

> step 401 / 8192 t = 0.4895020E-02 dt = 1.22E-05 moved 10 in 0.0051 cpu-s <

 radiation diffusion controlling timestep on           12  particles
> step 402 / 8192 t = 0.4907227E-02 dt = 1.22E-05 moved 517 in 0.016 cpu-s <
 WARNING! evolve: N gas particles with energy = 0 : N = 160

 radiation diffusion controlling timestep on           74  particles
> step 202 / 4096 t = 0.4931641E-02 dt = 2.44E-05 moved 2203 in 0.056 cpu-s <
 WARNING! evolve: N gas particles with energy = 0 : N = 160

> step 809 / 16384 t = 0.4937744E-02 dt = 6.10E-06 moved 3 in 0.0045 cpu-s <

 radiation diffusion controlling timestep on            4  particles
 B-cleaning controlling timestep on           12  particles
> step 810 / 16384 t = 0.4943848E-02 dt = 6.10E-06 moved 137 in 0.0082 cpu-s <
 WARNING! evolve: N gas particles with energy = 0 : N = 160

> step 103681 / 2097152 t = 0.4943895E-02 dt = 4.77E-08 moved 1 in 0.0037 cpu-s <

 radiation diffusion controlling timestep on            1  particles
 B-cleaning controlling timestep on           12  particles
> step 103682 / 2097152 t = 0.4943943E-02 dt = 4.77E-08 moved 59 in 0.0053 cpu-s <
 WARNING! evolve: N gas particles with energy = 0 : N = 160

> step 414729 / 8388608 t = 0.4943955E-02 dt = 1.19E-08 moved 1 in 0.0036 cpu-s <

 B-cleaning controlling timestep on           16  particles
> step 414730 / 8388608 t = 0.4943967E-02 dt = 1.19E-08 moved 57 in 0.0052 cpu-s <
 WARNING! evolve: N gas particles with energy = 0 : N = 160

 radiation diffusion controlling timestep on            8  particles
 B-cleaning controlling timestep on           57  particles
> step 207366 / 4194304 t = 0.4943991E-02 dt = 2.38E-08 moved 350 in 0.014 cpu-s <
 (buffering remaining warnings... N gas particles with energy = 0 : N = 160) 

 radiation diffusion controlling timestep on           43  particles
 B-cleaning controlling timestep on           64  particles
> step 103684 / 2097152 t = 0.4944038E-02 dt = 4.77E-08 moved 1111 in 0.031 cpu-s <

> step 26543105 / 536870912 t = 0.4944039E-02 dt = 1.86E-10 moved 1 in 0.0043 cpu-s <

get_newbin: dt_ibin(0)   =    1.0000000E-01
get_newbin: dt_ibin(max) =    1.8626451E-10
get_newbin: dt = dt_radiation    

 FATAL ERROR! get_newbin: step too small: bin would exceed maximum : dt =  4.852E-11
```

**Comment by jameswurster** [comment] 2020-06-03 10:52
Hello
This is not a B-cleaning issue.  I recently separated dtclean from dtc, so we now explicitly see when dtclean < dtc.  

This fatal error is caused when dtradi becomes too small.  The offending code is 
          if ((rad(iradxi,i) + dtradi*drad(iradxi,i)) < 0) then
             if (rad(iradxi,i) > 0.) dtradi = -rad(iradxi,i)/drad(iradxi,i)/1e1
             call warning('force','radiation may become negative, limiting timestep')
          endif

Sedov will successfully run if the second if-statement is replaced with 
             if (rad(iradxi,i) > 0. .and. drad(iradxi,i) > 0.) dtradi = -rad(iradxi,i)/drad(iradxi,i)/1e1
however I did not make this change since I'm not sure if drad < 0 legitimately.  Note that sedov does not successfully run for
             if (rad(iradxi,i) > 0. .and. abs(drad(iradxi,i) > 0.)) dtradi = -rad(iradxi,i)/drad(iradxi,i)/1e1
or
             dtradi = -0.1*rad(iradxi,i)/(drad(iradxi,i)+epsilon(dtradi))

Although this is the bug, I will let someone more familiar with radiation fix it.

**Comment by danieljprice** [comment] 2020-06-03 12:32
thanks, I will fix the radiation issue. However, even without the fatal error running "make testkd" reports "B cleaning controlling timestep", which should not be the case.

**Comment by jameswurster** [comment] 2020-06-03 12:43
G'day

The problem is that mhd = .true. in this test, so we are evolving the B-field even though it is zero.  The cleaning timestep is necessarily calculated and is 0.5*Ccour*h/(1.0*c_s).  This timestep was always controlling dt, but before dtclean was quickly hidden via
dtc  = min(dtc, dtclean)
so we didn't know how influential it was.  It wasn't until I started explicitly testing this and I separated out dtclean did we realise its effects.

In the sedov test case, we could set
psidecayfac = 0.
which will prevent the cleaning (and dtclean) from being used...
Alternatively, in force, we could replace
          if (psidecayfac > 0.) then
with
          if (psidecayfac > 0. .and. B2i > 0.) then


Cheers
James

________________________________

**Comment by danieljprice** [comment] 2020-06-03 12:45
even more interesting. Do you remember if there is a reason why the cleaning timestep is 0.5*C_cour? I guess that is the reason it controls the timestep

**Comment by jameswurster** [comment] 2020-06-03 12:48
The notes in the code say
"the factor of 0.5 is empirical, from checking when overcleaning with ind. timesteps is stable"
I interpret that to mean it was added by Terry for stability.

That probably means that we should not remove it.

**Comment by danieljprice** [comment] 2020-06-03 12:51
ok, but this is only an issue if we are using overcleaning, so the 0.5 should not be necessary unless overcleaningfac is > 1.0

**Comment by jameswurster** [comment] 2020-06-03 12:56
That seems reasonable... so we should instead use 
             hdivbbmax = max( overcleanfac, 10.*hdivbbmax, 10.*fsum(ihdivBBmax) )
             hdivbbmax = min( hdivbbmax, hdivbbmax_max )
             if (hdivbbmax > 1.0) hdivbbmax = 2.0*hdivbbmax
             dtclean   = C_cour*hi/(hdivbbmax * vwavei + epsilon(0.))

**Comment by danieljprice** [comment] 2020-06-03 13:00
I think just with the second last line replaced with 

```if (overcleanfac > 1.0) hdivbbmax = 2.0*hdivbbmax```

PS: use three backticks for embedding code snippets

**Comment by jameswurster** [comment] 2020-06-03 13:04
ok.
I'll make the modifications and submit them.

**Comment by jameswurster** [comment] 2021-03-23 13:38
This issue should be resolved.

dtclean was a limiting timestep since dtclean included epsilon in the denominator while dtc was only calculated if the denominator > tiny.  Setting both to tiny now removes dtclean being the limiting timestep.  For added stability, we decreased C_cour, and likewise decreased the tolerance on the energy error.

The issue where different results were obtained using and not using MPI no longer exists, so dtclean <= dtc in the hydro limit.

We fixed another bug where gmw was not defined in test_sedov, thus was 2.38 if only the Sedov test was run (which would fail) yet 2.0 if the entire testsuite was run (and would pass).

**Comment by jameswurster** [comment] 2021-04-21 08:50
This issue is (again) resolved in commit ea06b49.  Although it appeared resolved in previous commits, the patch did not seem consistent.  The issue *should* be fixed now.

**Comment by danieljprice** [comment] 2021-05-12 06:33
can this issue be closed?

**Comment by jameswurster** [comment] 2021-05-12 08:07
This issue is complete and can be closed.

**Closed** 2021-05-14 03:29 UTC
Labels: bug
