### ISSUE TITLE
Error appeared when evoluting star.in using star or grstar setup(GR=yes)

### ISSUE THREAD

**Issue by Shigaharuki3012** [danieljprice/phantom#402] opened 2023-04-06 05:56 UTC
Steps followed:
```
/phantom/scripts/writemake.sh star > Makefile
make SETUP=star GR=yes
make setup
./phantomsetup star.setup
```
I choose **Polytrope** , **524000** particles and automatically relaxing the star.
After normally relaxing the star:
`./phantom star.in
`
Then errors:
```
<<< finished reading (hydro) file 


 ERROR: units are incorrect for GR, need G = c = 1
  ...but we have G =    1.00000000000000       and c =    686.518075865455     
 
 Centre of mass is at (x,y,z) = ( 4.657E-18, -4.573E-18,  4.490E-18)

 FATAL ERROR! initial: errors in particle data from file : errors = 1
```
Same error appeared when using **grstar** setup.

**Comment by danieljprice** [comment] 2023-04-06 10:47
If you override compile time options on the command line you have to use GR=yes for both phantom and phantomsetup. Or better, just use grstar as the setup in the original writemake command…

**Comment by Shigaharuki3012** [comment] 2023-04-06 11:40
In fact if I use grstar as the setup in the original writemake command like :
```
/phantom/scripts/writemake.sh grstar > Makefile
make 
make setup
./phantomsetup star
```
After last step of the above:
```
--> ALLOCATING PART ARRAYS

 FATAL ERROR! memory: metrics allocation error
```
will appear.

**Comment by Shigaharuki3012** [comment] 2023-04-06 14:29
To add,same error above would not appear when using gfortran compiler.But when realxing star:
```
rstar  =    1.0000000085730454       mstar =   0.99935806369265401       tdyn =    1.1110774265470595     
 WARNING: Accrete particles: but Metric = Minkowski
 Centre of mass is at (x,y,z) = (-2.254E-18,  2.859E-20, -1.885E-20)
 Particle setup OK

 RELAX-A-STAR-O-MATIC: Etherm:  0.500     Epot: -0.856     R*:   1.00    
       WILL stop WHEN: dens error <   1.00% AND Ekin/Epot <   1.000E-07 OR Iter=1000


-------->   TIME =    0.000    : full dump written to file relax_00000   <--------


 ERROR! get_u0 in rho2dens: 1/sqrt(-v_mu v^mu) ---> non-negative: v_mu v^mu


 ERROR! get_u0 in prim2cons: 1/sqrt(-v_mu v^mu) ---> non-negative: v_mu v^mu


 ERROR! get_u0 in rho2dens: 1/sqrt(-v_mu v^mu) ---> non-negative: v_mu v^mu


 ERROR! get_u0 in prim2cons: 1/sqrt(-v_mu v^mu) ---> non-negative: v_mu v^mu


 ERROR! get_u0 in rho2dens: 1/sqrt(-v_mu v^mu) ---> non-negative: v_mu v^mu


 ERROR! get_u0 in prim2cons: 1/sqrt(-v_mu v^mu) ---> non-negative: v_mu v^mu


 ERROR! get_u0 in rho2dens: 1/sqrt(-v_mu v^mu) ---> non-negative: v_mu v^mu


 ERROR! get_u0 in prim2cons: 1/sqrt(-v_mu v^mu) ---> non-negative: v_mu v^mu


FATAL ERROR! cons2prim: could not solve rootfinding on particle 6277


```
would appear.

**Comment by Shigaharuki3012** [comment] 2023-04-11 14:13
Just to update,errors would not appear when relaxing star if using uniform density profile instead of polytrope for the star(For **grstar** case.That is,when GR=yes).

**Comment by danieljprice** [comment] 2023-05-18 00:30
I am closing this as from trying to reproduce this it seems like the issue is you are setting up a star with M=R=1 in relativity which implies a star with radius R = 1GM/c^2, which is smaller than it's Schwarzschild radius. Hence it is totally wrong to assume that the Newtonian self-gravity is a small perturbation to GR in this case

What is missing is that the code should at least give an error if you try to do this...

**Closed by danieljprice** 2023-05-18 00:30 UTC
