### ISSUE TITLE
segmentation fault when using phantomanalysis 

### ISSUE THREAD

**Issue by themikelau** [danieljprice/phantom#60] opened 2020-08-26 01:12 UTC
To reproduce, setup and run a sedov blast with the default setup. `make analysis` and `./phantomanalysis dump_00000`.

Error message:
```
>>./phantomanalysis blast_00000                                                                                                                              
 Phantom analysis (headerdt): You data, we analyse
 opening database from blast.in with 32 entries
Program received signal SIGSEGV: Segmentation fault - invalid memory reference.
Backtrace for this error:
#0  0x1091388cd
#1  0x109137cdd
#2  0x7fff6fc23b5c
[1]    61706 segmentation fault  ./phantomanalysis blast_00000
```

**Comment by danieljprice** [comment] 2020-08-26 01:20
pretty sure this is caused by the recent changes to the readwrite_dumps routines by @cpinte, the procedure pointers are not initialised. It's an easy fix, but in general the way this is implemented needs fixing, it is not nice to have to call an init_readwrite_dumps routine before calling readwrite_dumps.

**Comment by danieljprice** [comment] 2020-08-26 01:26
this affects A LOT of utilities, not just phantomanalysis, it would affect any utility that calls readwrite_dumps

**Comment by danieljprice** [comment] 2020-08-26 01:32
I pushed a fix, but there are still a number of other broken utilities that will need to be fixed

**Closed** 2021-05-17 07:24 UTC
