### ISSUE TITLE
Potential energy is not correctly calculated when sink-gas or sink-sink softening is used

### ISSUE THREAD

**Issue by miguelglezb** [danieljprice/phantom#62] opened 2020-09-01 05:44 UTC
Potential energy is not corrected calculated, which may due to the way the code is calculating the sink particle potential for gas particles inside softening length.

**Comment by danieljprice** [comment] 2020-10-01 05:57
I think this issue is related to the self-contribution to the potential energy when softening between sink particles is used. So would mainly occur when two sink particles come within each others softening length

**Comment by danieljprice** [comment] 2020-10-01 06:08
@miguelglezb I believe the commits above should fix the issue - can you please check this from your end?

**Comment by miguelglezb** [comment] 2020-10-01 06:10
Yes, I'll do a quick test and let you know.

**Comment by danieljprice** [comment] 2021-02-24 10:58
I found no bugs here so am closing this issue, please re-open it if the problem is still there

**Closed by danieljprice** 2021-02-24 10:58 UTC
